# .github/workflows/ci.yml

name: CI - Build Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_frontend:
    name: Build Frontend (React)
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x] 

    steps:
      # 1. Checkout: Clona el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node: Configura el entorno de Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      # 3. Instalación de dependencias del Frontend (en la carpeta frontend)
      - name: Install Frontend Dependencies (npm install)
        run: npm install
        working-directory: ./frontend 

      # 4. Construcción del Frontend (Build)
      - name: Build Frontend (npm run build)
        run: npm run build
        working-directory: ./frontend